import type { ProjectConfig } from '@saas-factory/types';

/**
 * 開發測試用範本設定。
 * 真實 client 部署時應由 factory app 依藍圖產生覆寫此檔。
 * 預設啟用所有模組以利後續 goal 的整合測試。
 */
export const projectConfig: ProjectConfig = {
  meta: {
    projectId: 'dev',
    clientName: '開發測試',
    brandName: 'SaaS Factory Demo',
    domain: 'localhost:3000',
    contactEmail: 'dev@example.com',
    createdAt: new Date('2026-05-15T00:00:00.000Z'),
    version: '0.1.0',
  },

  siteTypes: ['cms', 'shop', 'course', 'lp', 'blog'],

  tenancy: {
    enabled: false,
    mode: 'single',
    sharedMembers: false,
    sharedInventory: false,
    sharedOrders: false,
  },

  modules: {
    shop: {
      multiVariant: true,
      preOrder: true,
      digitalProducts: true,
      productVideo: true,
      product3DAR: false,
      inventory: {
        enabled: true,
        preDeduct: true,
        preDeductTTL: 900,
        safetyStock: true,
        multiWarehouse: false,
        batchTracking: false,
        crossChannelSync: false,
      },
      guestCheckout: true,
      onePageCheckout: true,
      shippingCalculator: true,
      memberTiers: true,
      points: true,
      storedValue: false,
      birthdayReward: true,
      wishlist: true,
      reviews: true,
      upsell: { orderBump: true, oneClickUpsell: true, crossSell: true },
      flashSale: true,
      groupBuy: false,
      subscription: false,
      returnRequest: true,
      partialRefund: true,
      exchangeOrder: true,
      feeds: { googleMerchant: true, metaCatalog: true, lineLAP: false, tiktok: false },
      fraudDetection: false,
    },
    course: {
      videoProvider: 'bunny',
      audioOnly: false,
      pdfWithAnnotations: true,
      interactiveExercise: true,
      watermark: { enabled: true, dynamic: true, content: 'email' },
      drm: false,
      deviceLimit: 3,
      notesTimestamped: true,
      inVideoQuestion: true,
      speedMemory: true,
      autoplay: false,
      offlineDownload: false,
      backgroundPlay: false,
      quiz: true,
      assignment: true,
      peerReview: false,
      certificate: { enabled: true, blockchain: false, linkedInShare: true, expiration: false },
      discussion: true,
      studentDirectory: false,
      externalCommunity: 'line',
      pricingMode: ['one-time', 'subscription'],
      prelaunch: { crowdfunding: false, earlyBird: true },
      liveClass: { enabled: false, provider: 'zoom', autoRecord: false },
      b2bEnterprise: false,
      sso: [],
      multiInstructor: false,
      instructorRevShare: false,
      certifications: { govLearningHours: false, cpe: false },
    },
    lp: {
      blockEditor: true,
      customBlocks: true,
      versionControl: true,
      scheduledPublish: true,
      passwordProtectedPreview: true,
      formCheckout: true,
      cashOnDelivery: true,
      threeTierPricing: true,
      orderBump: true,
      oneClickUpsell: true,
      upsellLayers: 2,
      exitIntent: true,
      liveNotifications: true,
      countdown: { enabled: true, mode: 'real' },
      visitorCounter: true,
      floatingCTA: true,
      heroVideo: true,
      multipleVersions: true,
      abTesting: true,
      utmTracking: true,
      customDomains: false,
      amp: false,
    },
    cms: {
      customPages: true,
      faq: true,
      contactForm: true,
      newsletter: true,
      teamProfile: true,
      portfolio: true,
      testimonials: true,
    },
    blog: {
      enabled: true,
      categories: true,
      tags: true,
      authors: true,
      comments: 'native',
      rssExport: true,
      relatedPosts: true,
      readingTime: true,
    },
    marketing: {
      automation: { enabled: true, triggers: ['order.completed', 'cart.abandoned'] },
      abandonedCart: { enabled: true, sequences: 3 },
      retargeting: true,
      affiliate: { enabled: false, multiLevel: false },
      referral: true,
      coupons: true,
      bannerScheduler: true,
    },
    reports: {
      dashboard: true,
      customReports: true,
      scheduledExport: false,
      comparisonViews: true,
      forecasting: false,
      anomalyAlerts: false,
    },
  },

  providers: {
    payment: {
      primary: 'newebpay',
      enabled: {
        newebpay: { methods: ['credit', 'atm', 'cvs', 'linepay'] },
      },
    },
    invoice: {
      provider: 'ezpay',
      mode: 'trigger',
      b2bSupport: true,
      carrierTypes: ['mobile', 'natural-person', 'donation', 'company'],
    },
    shipping: {
      enabled: {
        '7eleven': { codCheckout: true },
        'family-mart': { codCheckout: true },
        blackcat: true,
        pickup: true,
      },
      feeRules: 'weight-based',
    },
    notification: {
      email: 'resend',
      line: { messagingAPI: true, officialAccount: true },
      webPush: false,
    },
    storage: {
      primary: 'r2',
      cdn: 'cloudflare',
    },
    video: {
      primary: 'bunny',
    },
  },

  theme: {
    preset: 'modern-minimal',
    tokens: {
      colors: {
        primary: '#1a1a1a',
        secondary: '#666666',
        accent: '#0066ff',
        background: '#ffffff',
        foreground: '#1a1a1a',
      },
      radius: 'soft',
      fontFamily: {
        sans: 'system-ui',
        serif: 'Georgia',
        display: 'system-ui',
      },
      spacing: 'normal',
      shadow: 'subtle',
    },
  },

  seo: {
    defaultTitle: 'SaaS Factory Demo',
    defaultDescription: '多類型網站工廠 — 開發測試實例',
    dynamicOGImage: false,
    schemaOrg: {
      organization: true,
      localBusiness: false,
      product: true,
      course: true,
      article: true,
      breadcrumb: true,
      faq: true,
      event: false,
    },
    sitemap: true,
    robots: true,
    hreflang: false,
  },

  analytics: {},

  i18n: {
    enabled: false,
    defaultLocale: 'zh-TW',
    locales: ['zh-TW'],
    fallbackLocale: 'zh-TW',
    multiCurrency: false,
    currencies: [{ code: 'TWD', symbol: 'NT$', taxIncluded: true }],
    multiTimezone: false,
  },

  compliance: {
    cookieConsent: true,
    privacyPolicy: true,
    termsOfService: true,
    refundPolicy: true,
    taiwan: {
      personalDataAct: true,
      consumerProtectionAct: true,
      sevenDayRefund: true,
      invoiceCompliance: true,
    },
    twoFactorAuth: true,
    auditLog: true,
    dataExport: true,
    dataDeletion: true,
  },
};
