packages:
  - 'apps/*'
  - 'packages/*'
  - 'packages/config/*'
  - 'packages/core/*'
  - 'packages/cms/*'
  - 'packages/payment/*'
  - 'packages/invoice/*'
  - 'packages/shipping/*'
  - 'packages/notification/*'
  - 'packages/ui/*'
  - 'packages/shop/*'
  - 'packages/marketing/*'
  - 'packages/course/*'
  - 'packages/lp/*'
  - 'packages/factory/*'
  - 'packages/frontend/*'
