import { generateColorScale } from '../color-scale.js';

import {
  SHARED_BREAKPOINTS,
  SHARED_DURATION,
  SHARED_EASING,
  SHARED_FONT_SIZE,
  SHARED_FONT_WEIGHT,
  SHARED_LETTER_SPACING,
  SHARED_LINE_HEIGHT,
  SHARED_SPACING,
  SHARED_TRANSITION,
} from './_shared.js';

import type { DesignTokens } from '../types.js';

const primary = generateColorScale('#1a1a1a');
const accent = generateColorScale('#b8860b');
const neutral = generateColorScale('#4a4a4a');

export const luxuryEditorial: DesignTokens = {
  meta: {
    name: 'luxury-editorial',
    displayName: '奢華雜誌',
    description: 'Serif 主導、大量留白、金色點綴、雜誌排版。精品 / 珠寶 / 婚紗 / 高端不動產。',
    version: '1.0.0',
    recommendedIndustries: ['fashion-apparel', 'beauty-skincare', 'wedding', 'realestate', 'craft-design'],
    motionLevelRecommended: 3,
    darkModePrimary: 'light',
  },
  colors: {
    primary,
    secondary: neutral,
    accent,
    success: generateColorScale('#0f766e'),
    warning: generateColorScale('#b45309'),
    danger: generateColorScale('#991b1b'),
    info: generateColorScale('#1e3a8a'),
    neutral,
    surface: {
      base: '40 20% 98%',
      raised: '40 20% 100%',
      overlay: '40 20% 99%',
      sunken: '40 20% 96%',
      glass: '40 20% 98% / 0.85',
    },
    background: '40 20% 98%',
    foreground: '24 10% 10%',
    muted: '40 15% 92%',
    mutedForeground: '24 10% 40%',
    border: '40 15% 85%',
    borderSubtle: '40 15% 92%',
  },
  typography: {
    fontFamily: {
      sans: "'Inter', 'Noto Sans TC', system-ui, sans-serif",
      serif: "'Playfair Display', 'Noto Serif TC', serif",
      display: "'Playfair Display', 'Noto Serif TC', serif",
      mono: "'JetBrains Mono', monospace",
      handwriting: "'Allura', cursive",
    },
    fontWeight: SHARED_FONT_WEIGHT,
    fontSize: SHARED_FONT_SIZE,
    lineHeight: SHARED_LINE_HEIGHT,
    letterSpacing: SHARED_LETTER_SPACING,
    presets: {
      h1: { fontFamily: 'display', fontSize: '7xl', fontWeight: 'normal', lineHeight: 'tight', letterSpacing: 'tighter' },
      h2: { fontFamily: 'display', fontSize: '5xl', fontWeight: 'normal', lineHeight: 'tight', letterSpacing: 'tight' },
      h3: { fontFamily: 'display', fontSize: '4xl', fontWeight: 'normal', lineHeight: 'snug', letterSpacing: 'tight' },
      h4: { fontFamily: 'display', fontSize: '3xl', fontWeight: 'normal', lineHeight: 'snug', letterSpacing: 'normal' },
      h5: { fontFamily: 'serif', fontSize: '2xl', fontWeight: 'normal', lineHeight: 'snug', letterSpacing: 'normal' },
      h6: { fontFamily: 'serif', fontSize: 'xl', fontWeight: 'medium', lineHeight: 'normal', letterSpacing: 'normal' },
      body: { fontFamily: 'serif', fontSize: 'base', fontWeight: 'normal', lineHeight: 'loose', letterSpacing: 'normal' },
      bodyLarge: { fontFamily: 'serif', fontSize: 'lg', fontWeight: 'normal', lineHeight: 'loose', letterSpacing: 'normal' },
      bodySmall: { fontFamily: 'sans', fontSize: 'sm', fontWeight: 'normal', lineHeight: 'relaxed', letterSpacing: 'normal' },
      caption: { fontFamily: 'sans', fontSize: 'xs', fontWeight: 'normal', lineHeight: 'relaxed', letterSpacing: 'widest' },
      overline: { fontFamily: 'sans', fontSize: 'xs', fontWeight: 'semibold', lineHeight: 'normal', letterSpacing: 'widest' },
      button: { fontFamily: 'sans', fontSize: 'sm', fontWeight: 'medium', lineHeight: 'normal', letterSpacing: 'wider' },
      link: { fontFamily: 'serif', fontSize: 'base', fontWeight: 'medium', lineHeight: 'normal', letterSpacing: 'normal' },
      code: { fontFamily: 'mono', fontSize: 'sm', fontWeight: 'normal', lineHeight: 'normal', letterSpacing: 'normal' },
    },
  },
  radius: {
    none: '0',
    '2xs': '0.0625rem',
    xs: '0.125rem',
    sm: '0.25rem',
    md: '0.375rem',
    lg: '0.5rem',
    xl: '0.625rem',
    '2xl': '0.75rem',
    '3xl': '1rem',
    '4xl': '1.5rem',
    full: '9999px',
    button: '0.25rem',
    card: '0.5rem',
    input: '0.25rem',
    modal: '0.625rem',
    image: '0.375rem',
  },
  spacing: SHARED_SPACING,
  shadow: {
    none: 'none',
    '2xs': '0 1px 2px rgb(0 0 0 / 0.04)',
    xs: '0 1px 3px rgb(0 0 0 / 0.06)',
    sm: '0 2px 4px rgb(0 0 0 / 0.05)',
    md: '0 6px 12px rgb(0 0 0 / 0.08)',
    lg: '0 12px 24px rgb(0 0 0 / 0.1)',
    xl: '0 24px 48px rgb(0 0 0 / 0.12)',
    '2xl': '0 36px 72px rgb(0 0 0 / 0.18)',
    inner: 'inset 0 2px 4px rgb(0 0 0 / 0.06)',
    soft: '0 16px 48px rgb(0 0 0 / 0.08)',
    glow: '0 0 60px hsl(var(--color-accent-500) / 0.25)',
    glowAccent: '0 0 80px hsl(var(--color-accent-400) / 0.35)',
    colored: '0 20px 40px -10px hsl(var(--color-accent-500) / 0.2)',
    drop: '0 32px 64px rgb(0 0 0 / 0.12)',
    float: '0 48px 80px -16px rgb(0 0 0 / 0.18)',
    layered:
      '0 2px 4px rgb(0 0 0 / 0.05), 0 8px 16px rgb(0 0 0 / 0.06), 0 24px 48px rgb(0 0 0 / 0.1)',
    card: '0 2px 4px rgb(0 0 0 / 0.04), 0 8px 16px rgb(0 0 0 / 0.06)',
    cardHover: '0 8px 16px rgb(0 0 0 / 0.08), 0 24px 48px rgb(0 0 0 / 0.12)',
    button: '0 2px 4px rgb(0 0 0 / 0.06)',
    buttonHover: '0 6px 12px rgb(0 0 0 / 0.12)',
    modal: '0 32px 64px rgb(0 0 0 / 0.25)',
    popover: '0 12px 24px rgb(0 0 0 / 0.12)',
    dropdown: '0 8px 16px rgb(0 0 0 / 0.1)',
  },
  motion: {
    duration: SHARED_DURATION,
    easing: SHARED_EASING,
    transition: {
      ...SHARED_TRANSITION,
      base: 'all 400ms cubic-bezier(0.4, 0, 0.2, 1)',
    },
    motionLevel: 3,
    respectReducedMotion: true,
  },
  density: 'spacious',
  interaction: {
    hover: { scale: 1.015, translateY: '-3px', shadowIntensity: 1.8, brightness: 1.03 },
    active: { scale: 0.99, translateY: '0' },
    focus: {
      ringWidth: '2px',
      ringOffset: '3px',
      ringColor: 'hsl(var(--color-accent-500) / 0.5)',
      ringStyle: 'solid',
    },
    spotlight: { enabled: true, size: '400px', intensity: 0.15 },
    magnetic: { enabled: false, strength: 0.2, range: 80 },
  },
  effects: {
    glass: { blur: 'blur(32px)', saturation: 200, bgOpacity: 0.85, borderOpacity: 0.15 },
    gradients: {
      primary: 'linear-gradient(135deg, hsl(var(--color-primary-700)), hsl(var(--color-primary-900)))',
      accent: 'linear-gradient(135deg, hsl(var(--color-accent-400)), hsl(var(--color-accent-700)))',
      mesh: 'radial-gradient(at 20% 20%, hsl(var(--color-accent-500) / 0.2), transparent 50%), radial-gradient(at 80% 80%, hsl(var(--color-primary-500) / 0.15), transparent 50%)',
      radial: 'radial-gradient(circle, hsl(var(--color-accent-500) / 0.2), transparent 60%)',
      conic: 'conic-gradient(from 90deg, hsl(var(--color-accent-300)), hsl(var(--color-accent-600)))',
      sunset: 'linear-gradient(135deg, #fbbf24, #b45309)',
      aurora: 'linear-gradient(135deg, #818cf8, #c084fc)',
      ocean: 'linear-gradient(135deg, #38bdf8, #1e40af)',
      forest: 'linear-gradient(135deg, #65a30d, #166534)',
    },
    patterns: { noise: true, grid: false, dots: false, waves: false },
    glow: { enabled: true, color: 'hsl(var(--color-accent-500))', size: '300px', intensity: 0.2 },
    perspective: { enabled: true, distance: '1200px', tilt: { max: 6, reset: 600 } },
  },
  breakpoints: SHARED_BREAKPOINTS,
};
