import { generateColorScale } from '../color-scale.js';

import {
  SHARED_BREAKPOINTS,
  SHARED_DURATION,
  SHARED_EASING,
  SHARED_FONT_SIZE,
  SHARED_FONT_WEIGHT,
  SHARED_LETTER_SPACING,
  SHARED_LINE_HEIGHT,
  SHARED_SPACING,
  SHARED_TRANSITION,
} from './_shared.js';

import type { DesignTokens } from '../types.js';

const primary = generateColorScale('#1f2937');
const accent = generateColorScale('#3b82f6');
const neutral = generateColorScale('#525252');

export const modernMinimal: DesignTokens = {
  meta: {
    name: 'modern-minimal',
    displayName: '極簡現代',
    description: '大量留白、單色為主、克制裝飾、強調內容。SaaS / 顧問 / 個人品牌首選。',
    version: '1.0.0',
    recommendedIndustries: ['saas-software', 'consulting', 'personal-brand', 'legal-accounting'],
    motionLevelRecommended: 2,
    darkModePrimary: 'both',
  },
  colors: {
    primary,
    secondary: neutral,
    accent,
    success: generateColorScale('#10b981'),
    warning: generateColorScale('#f59e0b'),
    danger: generateColorScale('#ef4444'),
    info: generateColorScale('#3b82f6'),
    neutral,
    surface: {
      base: '0 0% 100%',
      raised: '0 0% 99%',
      overlay: '0 0% 100%',
      sunken: '0 0% 98%',
      glass: '0 0% 100% / 0.7',
    },
    background: '0 0% 100%',
    foreground: '222 47% 11%',
    muted: '210 40% 96%',
    mutedForeground: '215 16% 47%',
    border: '214 32% 91%',
    borderSubtle: '214 32% 95%',
    dark: {
      primary,
      secondary: neutral,
      accent,
      success: generateColorScale('#10b981'),
      warning: generateColorScale('#f59e0b'),
      danger: generateColorScale('#ef4444'),
      info: generateColorScale('#3b82f6'),
      neutral,
      surface: {
        base: '222 47% 8%',
        raised: '222 47% 11%',
        overlay: '222 47% 14%',
        sunken: '222 47% 6%',
        glass: '222 47% 11% / 0.7',
      },
      background: '222 47% 8%',
      foreground: '210 40% 98%',
      muted: '217 33% 17%',
      mutedForeground: '215 20% 65%',
      border: '217 33% 20%',
      borderSubtle: '217 33% 15%',
    },
  },
  typography: {
    fontFamily: {
      sans: "'Inter', 'Noto Sans TC', system-ui, sans-serif",
      serif: "'Source Serif Pro', 'Noto Serif TC', serif",
      display: "'Inter', 'Noto Sans TC', system-ui, sans-serif",
      mono: "'JetBrains Mono', 'Fira Code', monospace",
    },
    fontWeight: SHARED_FONT_WEIGHT,
    fontSize: SHARED_FONT_SIZE,
    lineHeight: SHARED_LINE_HEIGHT,
    letterSpacing: SHARED_LETTER_SPACING,
    presets: {
      h1: { fontFamily: 'sans', fontSize: '5xl', fontWeight: 'bold', lineHeight: 'tight', letterSpacing: 'tight' },
      h2: { fontFamily: 'sans', fontSize: '4xl', fontWeight: 'bold', lineHeight: 'tight', letterSpacing: 'tight' },
      h3: { fontFamily: 'sans', fontSize: '3xl', fontWeight: 'semibold', lineHeight: 'snug', letterSpacing: 'normal' },
      h4: { fontFamily: 'sans', fontSize: '2xl', fontWeight: 'semibold', lineHeight: 'snug', letterSpacing: 'normal' },
      h5: { fontFamily: 'sans', fontSize: 'xl', fontWeight: 'semibold', lineHeight: 'snug', letterSpacing: 'normal' },
      h6: { fontFamily: 'sans', fontSize: 'lg', fontWeight: 'semibold', lineHeight: 'normal', letterSpacing: 'normal' },
      body: { fontFamily: 'sans', fontSize: 'base', fontWeight: 'normal', lineHeight: 'relaxed', letterSpacing: 'normal' },
      bodyLarge: { fontFamily: 'sans', fontSize: 'lg', fontWeight: 'normal', lineHeight: 'relaxed', letterSpacing: 'normal' },
      bodySmall: { fontFamily: 'sans', fontSize: 'sm', fontWeight: 'normal', lineHeight: 'normal', letterSpacing: 'normal' },
      caption: { fontFamily: 'sans', fontSize: 'xs', fontWeight: 'normal', lineHeight: 'normal', letterSpacing: 'wide' },
      overline: { fontFamily: 'sans', fontSize: 'xs', fontWeight: 'semibold', lineHeight: 'normal', letterSpacing: 'widest' },
      button: { fontFamily: 'sans', fontSize: 'sm', fontWeight: 'medium', lineHeight: 'normal', letterSpacing: 'normal' },
      link: { fontFamily: 'sans', fontSize: 'base', fontWeight: 'medium', lineHeight: 'normal', letterSpacing: 'normal' },
      code: { fontFamily: 'mono', fontSize: 'sm', fontWeight: 'normal', lineHeight: 'normal', letterSpacing: 'normal' },
    },
  },
  radius: {
    none: '0',
    '2xs': '0.125rem',
    xs: '0.25rem',
    sm: '0.5rem',
    md: '0.75rem',
    lg: '0.875rem',
    xl: '1rem',
    '2xl': '1.25rem',
    '3xl': '1.5rem',
    '4xl': '2rem',
    full: '9999px',
    button: '0.5rem',
    card: '0.875rem',
    input: '0.5rem',
    modal: '1rem',
    image: '0.75rem',
  },
  spacing: SHARED_SPACING,
  shadow: {
    none: 'none',
    '2xs': '0 1px 1px rgb(0 0 0 / 0.02)',
    xs: '0 1px 2px rgb(0 0 0 / 0.04)',
    sm: '0 1px 2px rgb(0 0 0 / 0.05), 0 1px 4px rgb(0 0 0 / 0.04)',
    md: '0 4px 6px -1px rgb(0 0 0 / 0.06), 0 2px 4px -2px rgb(0 0 0 / 0.04)',
    lg: '0 10px 15px -3px rgb(0 0 0 / 0.06), 0 4px 6px -4px rgb(0 0 0 / 0.05)',
    xl: '0 20px 25px -5px rgb(0 0 0 / 0.08), 0 8px 10px -6px rgb(0 0 0 / 0.05)',
    '2xl': '0 25px 50px -12px rgb(0 0 0 / 0.15)',
    inner: 'inset 0 2px 4px rgb(0 0 0 / 0.04)',
    soft: '0 8px 30px rgb(0 0 0 / 0.06)',
    glow: '0 0 40px hsl(var(--color-primary-500) / 0.2)',
    glowAccent: '0 0 40px hsl(var(--color-accent-500) / 0.3)',
    colored: '0 12px 24px -8px hsl(var(--color-primary-500) / 0.2)',
    drop: '0 16px 40px rgb(0 0 0 / 0.1)',
    float: '0 24px 48px -12px rgb(0 0 0 / 0.18)',
    layered:
      '0 1px 2px rgb(0 0 0 / 0.04), 0 4px 12px rgb(0 0 0 / 0.06), 0 16px 32px rgb(0 0 0 / 0.08)',
    card: '0 1px 2px rgb(0 0 0 / 0.04), 0 4px 12px rgb(0 0 0 / 0.06)',
    cardHover: '0 4px 8px rgb(0 0 0 / 0.06), 0 12px 24px rgb(0 0 0 / 0.1)',
    button: '0 1px 2px rgb(0 0 0 / 0.06)',
    buttonHover: '0 4px 8px rgb(0 0 0 / 0.1)',
    modal: '0 24px 48px -12px rgb(0 0 0 / 0.25)',
    popover: '0 8px 16px -4px rgb(0 0 0 / 0.12)',
    dropdown: '0 4px 12px rgb(0 0 0 / 0.08)',
  },
  motion: {
    duration: SHARED_DURATION,
    easing: SHARED_EASING,
    transition: SHARED_TRANSITION,
    motionLevel: 2,
    respectReducedMotion: true,
  },
  density: 'normal',
  interaction: {
    hover: { scale: 1.02, translateY: '-2px', shadowIntensity: 1.5, brightness: 1.05 },
    active: { scale: 0.98, translateY: '1px' },
    focus: {
      ringWidth: '3px',
      ringOffset: '2px',
      ringColor: 'hsl(var(--color-primary-500) / 0.4)',
      ringStyle: 'solid',
    },
    spotlight: { enabled: false, size: '300px', intensity: 0.2 },
    magnetic: { enabled: false, strength: 0.3, range: 100 },
  },
  effects: {
    glass: { blur: 'blur(24px)', saturation: 180, bgOpacity: 0.7, borderOpacity: 0.2 },
    gradients: {
      primary: 'linear-gradient(135deg, hsl(var(--color-primary-500)), hsl(var(--color-primary-700)))',
      accent: 'linear-gradient(135deg, hsl(var(--color-accent-400)), hsl(var(--color-accent-600)))',
      mesh: 'radial-gradient(at 0% 0%, hsl(var(--color-accent-400) / 0.3), transparent 50%), radial-gradient(at 100% 100%, hsl(var(--color-primary-500) / 0.2), transparent 50%)',
      radial: 'radial-gradient(circle, hsl(var(--color-primary-500) / 0.15), transparent 70%)',
      conic: 'conic-gradient(from 180deg, hsl(var(--color-primary-500)), hsl(var(--color-accent-500)))',
      sunset: 'linear-gradient(135deg, #fef3c7, #fde68a)',
      aurora: 'linear-gradient(135deg, #a5b4fc, #c7d2fe)',
      ocean: 'linear-gradient(135deg, #bae6fd, #7dd3fc)',
      forest: 'linear-gradient(135deg, #bbf7d0, #86efac)',
    },
    patterns: { noise: false, grid: false, dots: false, waves: false },
    glow: { enabled: false, color: 'hsl(var(--color-primary-500))', size: '200px', intensity: 0.3 },
    perspective: { enabled: false, distance: '1000px', tilt: { max: 0, reset: 400 } },
  },
  breakpoints: SHARED_BREAKPOINTS,
};
