import { generateColorScale } from '../color-scale.js';

import {
  SHARED_BREAKPOINTS,
  SHARED_DURATION,
  SHARED_EASING,
  SHARED_FONT_SIZE,
  SHARED_FONT_WEIGHT,
  SHARED_LETTER_SPACING,
  SHARED_LINE_HEIGHT,
  SHARED_SPACING,
  SHARED_TRANSITION,
} from './_shared.js';

import type { DesignTokens } from '../types.js';

const primary = generateColorScale('#3f6212');
const accent = generateColorScale('#84cc16');
const neutral = generateColorScale('#57534e');

export const organicWellness: DesignTokens = {
  meta: {
    name: 'organic-wellness',
    displayName: '有機健康',
    description: '大地色系、自然圓潤、有溫度。保健食品 / 餐飲 / 寵物 / 母嬰 / SPA。',
    version: '1.0.0',
    recommendedIndustries: ['supplement', 'baby-mom', 'pet-supplies', 'food-snacks', 'salon', 'restaurant', 'fitness-gym'],
    motionLevelRecommended: 3,
    darkModePrimary: 'light',
  },
  colors: {
    primary,
    secondary: neutral,
    accent,
    success: generateColorScale('#15803d'),
    warning: generateColorScale('#d97706'),
    danger: generateColorScale('#b91c1c'),
    info: generateColorScale('#0369a1'),
    neutral,
    surface: {
      base: '60 30% 98%',
      raised: '60 30% 100%',
      overlay: '60 30% 99%',
      sunken: '60 30% 95%',
      glass: '60 30% 98% / 0.8',
    },
    background: '60 30% 98%',
    foreground: '60 20% 12%',
    muted: '60 25% 92%',
    mutedForeground: '60 15% 40%',
    border: '60 20% 86%',
    borderSubtle: '60 20% 92%',
  },
  typography: {
    fontFamily: {
      sans: "'Manrope', 'Noto Sans TC', system-ui, sans-serif",
      serif: "'Lora', 'Noto Serif TC', serif",
      display: "'Fraunces', 'Noto Serif TC', serif",
      mono: "'JetBrains Mono', monospace",
    },
    fontWeight: SHARED_FONT_WEIGHT,
    fontSize: SHARED_FONT_SIZE,
    lineHeight: SHARED_LINE_HEIGHT,
    letterSpacing: SHARED_LETTER_SPACING,
    presets: {
      h1: { fontFamily: 'display', fontSize: '6xl', fontWeight: 'semibold', lineHeight: 'tight', letterSpacing: 'tight' },
      h2: { fontFamily: 'display', fontSize: '5xl', fontWeight: 'semibold', lineHeight: 'tight', letterSpacing: 'tight' },
      h3: { fontFamily: 'display', fontSize: '3xl', fontWeight: 'semibold', lineHeight: 'snug', letterSpacing: 'normal' },
      h4: { fontFamily: 'sans', fontSize: '2xl', fontWeight: 'semibold', lineHeight: 'snug', letterSpacing: 'normal' },
      h5: { fontFamily: 'sans', fontSize: 'xl', fontWeight: 'semibold', lineHeight: 'snug', letterSpacing: 'normal' },
      h6: { fontFamily: 'sans', fontSize: 'lg', fontWeight: 'medium', lineHeight: 'normal', letterSpacing: 'normal' },
      body: { fontFamily: 'sans', fontSize: 'base', fontWeight: 'normal', lineHeight: 'relaxed', letterSpacing: 'normal' },
      bodyLarge: { fontFamily: 'sans', fontSize: 'lg', fontWeight: 'normal', lineHeight: 'relaxed', letterSpacing: 'normal' },
      bodySmall: { fontFamily: 'sans', fontSize: 'sm', fontWeight: 'normal', lineHeight: 'normal', letterSpacing: 'normal' },
      caption: { fontFamily: 'sans', fontSize: 'xs', fontWeight: 'normal', lineHeight: 'normal', letterSpacing: 'wide' },
      overline: { fontFamily: 'sans', fontSize: 'xs', fontWeight: 'semibold', lineHeight: 'normal', letterSpacing: 'widest' },
      button: { fontFamily: 'sans', fontSize: 'sm', fontWeight: 'semibold', lineHeight: 'normal', letterSpacing: 'normal' },
      link: { fontFamily: 'sans', fontSize: 'base', fontWeight: 'medium', lineHeight: 'normal', letterSpacing: 'normal' },
      code: { fontFamily: 'mono', fontSize: 'sm', fontWeight: 'normal', lineHeight: 'normal', letterSpacing: 'normal' },
    },
  },
  radius: {
    none: '0',
    '2xs': '0.25rem',
    xs: '0.375rem',
    sm: '0.625rem',
    md: '0.875rem',
    lg: '1rem',
    xl: '1.25rem',
    '2xl': '1.5rem',
    '3xl': '2rem',
    '4xl': '2.5rem',
    full: '9999px',
    button: '0.875rem',
    card: '1.25rem',
    input: '0.75rem',
    modal: '1.5rem',
    image: '1rem',
  },
  spacing: SHARED_SPACING,
  shadow: {
    none: 'none',
    '2xs': '0 1px 2px rgb(63 98 18 / 0.04)',
    xs: '0 1px 3px rgb(63 98 18 / 0.06)',
    sm: '0 2px 4px rgb(63 98 18 / 0.05)',
    md: '0 4px 12px rgb(63 98 18 / 0.08)',
    lg: '0 8px 20px rgb(63 98 18 / 0.1)',
    xl: '0 16px 32px rgb(63 98 18 / 0.12)',
    '2xl': '0 24px 48px rgb(63 98 18 / 0.18)',
    inner: 'inset 0 2px 4px rgb(63 98 18 / 0.06)',
    soft: '0 12px 32px rgb(63 98 18 / 0.08)',
    glow: '0 0 50px hsl(var(--color-primary-500) / 0.25)',
    glowAccent: '0 0 60px hsl(var(--color-accent-400) / 0.3)',
    colored: '0 16px 32px -8px hsl(var(--color-primary-500) / 0.2)',
    drop: '0 24px 48px rgb(63 98 18 / 0.12)',
    float: '0 32px 64px -12px rgb(63 98 18 / 0.18)',
    layered:
      '0 2px 4px rgb(63 98 18 / 0.04), 0 6px 16px rgb(63 98 18 / 0.06), 0 20px 40px rgb(63 98 18 / 0.08)',
    card: '0 2px 4px rgb(63 98 18 / 0.04), 0 6px 16px rgb(63 98 18 / 0.06)',
    cardHover: '0 6px 12px rgb(63 98 18 / 0.08), 0 20px 40px rgb(63 98 18 / 0.12)',
    button: '0 2px 4px rgb(63 98 18 / 0.06)',
    buttonHover: '0 6px 12px rgb(63 98 18 / 0.12)',
    modal: '0 24px 48px rgb(63 98 18 / 0.25)',
    popover: '0 8px 20px rgb(63 98 18 / 0.12)',
    dropdown: '0 4px 16px rgb(63 98 18 / 0.1)',
  },
  motion: {
    duration: SHARED_DURATION,
    easing: SHARED_EASING,
    transition: {
      ...SHARED_TRANSITION,
      base: 'all 300ms cubic-bezier(0.175, 0.885, 0.32, 1.275)',
    },
    motionLevel: 3,
    respectReducedMotion: true,
  },
  density: 'normal',
  interaction: {
    hover: { scale: 1.03, translateY: '-3px', shadowIntensity: 1.6, brightness: 1.05 },
    active: { scale: 0.97, translateY: '1px' },
    focus: {
      ringWidth: '3px',
      ringOffset: '2px',
      ringColor: 'hsl(var(--color-accent-500) / 0.5)',
      ringStyle: 'glow',
    },
    spotlight: { enabled: false, size: '300px', intensity: 0.2 },
    magnetic: { enabled: true, strength: 0.25, range: 80 },
  },
  effects: {
    glass: { blur: 'blur(20px)', saturation: 180, bgOpacity: 0.8, borderOpacity: 0.2 },
    gradients: {
      primary: 'linear-gradient(135deg, hsl(var(--color-primary-400)), hsl(var(--color-primary-700)))',
      accent: 'linear-gradient(135deg, hsl(var(--color-accent-300)), hsl(var(--color-accent-600)))',
      mesh: 'radial-gradient(at 20% 30%, hsl(var(--color-accent-400) / 0.3), transparent 50%), radial-gradient(at 80% 70%, hsl(var(--color-primary-500) / 0.25), transparent 50%)',
      radial: 'radial-gradient(circle, hsl(var(--color-primary-500) / 0.2), transparent 70%)',
      conic: 'conic-gradient(from 0deg, hsl(var(--color-accent-400)), hsl(var(--color-primary-500)))',
      sunset: 'linear-gradient(135deg, #fde68a, #f97316)',
      aurora: 'linear-gradient(135deg, #86efac, #4ade80)',
      ocean: 'linear-gradient(135deg, #67e8f9, #0891b2)',
      forest: 'linear-gradient(135deg, #84cc16, #166534)',
    },
    patterns: { noise: true, grid: false, dots: false, waves: true },
    glow: { enabled: true, color: 'hsl(var(--color-accent-500))', size: '250px', intensity: 0.25 },
    perspective: { enabled: false, distance: '1000px', tilt: { max: 0, reset: 400 } },
  },
  breakpoints: SHARED_BREAKPOINTS,
};
