import type { Industry, IndustryMetadata } from './index.js';

/**
 * 33 個產業 metadata 字典。
 *
 * Wizard 第 2 步「Industry 選擇」用此字典自動推薦：
 * - `recommendedSiteTypes`：第 2 步勾選
 * - `recommendedModules`：第 3 步勾選
 * - `recommendedPresetId`：第 4 步預選
 *
 * 客戶仍可手動覆寫。
 */
export const INDUSTRY_METADATA: Record<Industry, IndustryMetadata> = {
  // ===== 電商 10 =====
  supplement: {
    key: 'supplement',
    displayName: '保健食品',
    category: 'commerce',
    recommendedSiteTypes: ['shop', 'lp'],
    recommendedModules: [
      'shop.subscription',
      'shop.points',
      'marketing.abandoned-cart',
      'marketing.email-campaigns',
      'marketing.coupons',
    ],
    recommendedPresetId: 'organic-wellness',
  },
  'tech-accessories': {
    key: 'tech-accessories',
    displayName: '科技配件',
    category: 'commerce',
    recommendedSiteTypes: ['shop', 'lp'],
    recommendedModules: [
      'shop.product-variants',
      'lp.countdown',
      'marketing.flash-sale',
      'marketing.retargeting',
    ],
    recommendedPresetId: 'cyber-tech',
  },
  'fashion-apparel': {
    key: 'fashion-apparel',
    displayName: '服飾時尚',
    category: 'commerce',
    recommendedSiteTypes: ['shop'],
    recommendedModules: [
      'shop.product-variants',
      'shop.wishlist',
      'marketing.referral',
      'marketing.coupons',
    ],
    recommendedPresetId: 'street-edge',
  },
  'beauty-skincare': {
    key: 'beauty-skincare',
    displayName: '美妝保養',
    category: 'commerce',
    recommendedSiteTypes: ['shop', 'lp'],
    recommendedModules: [
      'shop.subscription',
      'shop.points',
      'marketing.line-marketing',
      'marketing.coupons',
    ],
    recommendedPresetId: 'beauty-boutique',
  },
  'home-furniture': {
    key: 'home-furniture',
    displayName: '居家家具',
    category: 'commerce',
    recommendedSiteTypes: ['shop', 'cms'],
    recommendedModules: ['shop.product-variants', 'lp.ab-test', 'marketing.email-campaigns'],
    recommendedPresetId: 'modern-minimal',
  },
  'food-snacks': {
    key: 'food-snacks',
    displayName: '食品零食',
    category: 'commerce',
    recommendedSiteTypes: ['shop', 'lp'],
    recommendedModules: [
      'shop.subscription',
      'marketing.coupons',
      'marketing.flash-sale',
      'marketing.line-marketing',
    ],
    recommendedPresetId: 'culinary-warmth',
  },
  'baby-mom': {
    key: 'baby-mom',
    displayName: '母嬰用品',
    category: 'commerce',
    recommendedSiteTypes: ['shop'],
    recommendedModules: [
      'shop.points',
      'shop.subscription',
      'marketing.line-marketing',
      'marketing.email-campaigns',
    ],
    recommendedPresetId: 'organic-wellness',
  },
  'pet-supplies': {
    key: 'pet-supplies',
    displayName: '寵物用品',
    category: 'commerce',
    recommendedSiteTypes: ['shop'],
    recommendedModules: ['shop.subscription', 'shop.points', 'marketing.referral'],
    recommendedPresetId: 'playful-bold',
  },
  'sports-outdoor': {
    key: 'sports-outdoor',
    displayName: '運動戶外',
    category: 'commerce',
    recommendedSiteTypes: ['shop'],
    recommendedModules: ['shop.product-variants', 'shop.wishlist', 'marketing.flash-sale'],
    recommendedPresetId: 'playful-bold',
  },
  'craft-design': {
    key: 'craft-design',
    displayName: '工藝設計',
    category: 'commerce',
    recommendedSiteTypes: ['shop', 'cms'],
    recommendedModules: ['lp.exit-intent', 'marketing.email-campaigns'],
    recommendedPresetId: 'artisan-craft',
  },

  // ===== 服務 8 =====
  'online-course': {
    key: 'online-course',
    displayName: '線上課程',
    category: 'service',
    recommendedSiteTypes: ['course', 'lp'],
    recommendedModules: [
      'course.watermark',
      'course.certificate',
      'course.quiz',
      'marketing.email-campaigns',
    ],
    recommendedPresetId: 'academy-warm',
  },
  'fitness-gym': {
    key: 'fitness-gym',
    displayName: '健身房',
    category: 'service',
    recommendedSiteTypes: ['lp', 'course'],
    recommendedModules: ['course.live', 'lp.sticky-cta', 'marketing.line-marketing'],
    recommendedPresetId: 'playful-bold',
  },
  salon: {
    key: 'salon',
    displayName: '美容沙龍',
    category: 'service',
    recommendedSiteTypes: ['lp', 'cms'],
    recommendedModules: ['lp.sticky-cta', 'marketing.line-marketing', 'marketing.loyalty'],
    recommendedPresetId: 'beauty-boutique',
  },
  'medical-aesthetic': {
    key: 'medical-aesthetic',
    displayName: '醫美診所',
    category: 'service',
    recommendedSiteTypes: ['lp', 'cms'],
    recommendedModules: ['lp.sticky-cta', 'lp.countdown', 'marketing.line-marketing'],
    recommendedPresetId: 'beauty-boutique',
  },
  'dental-clinic': {
    key: 'dental-clinic',
    displayName: '牙醫診所',
    category: 'service',
    recommendedSiteTypes: ['lp', 'cms'],
    recommendedModules: ['lp.sticky-cta', 'lp.notifications', 'marketing.email-campaigns'],
    recommendedPresetId: 'medical-clinical',
  },
  restaurant: {
    key: 'restaurant',
    displayName: '餐飲',
    category: 'service',
    recommendedSiteTypes: ['lp', 'cms'],
    recommendedModules: ['lp.sticky-cta', 'marketing.line-marketing', 'marketing.coupons'],
    recommendedPresetId: 'culinary-warmth',
  },
  'travel-tour': {
    key: 'travel-tour',
    displayName: '旅遊行程',
    category: 'service',
    recommendedSiteTypes: ['lp', 'cms'],
    recommendedModules: ['lp.sticky-cta', 'lp.countdown', 'marketing.email-campaigns'],
    recommendedPresetId: 'travel-escape',
  },
  wedding: {
    key: 'wedding',
    displayName: '婚禮婚紗',
    category: 'service',
    recommendedSiteTypes: ['lp', 'cms'],
    recommendedModules: ['lp.sticky-cta', 'marketing.line-marketing'],
    recommendedPresetId: 'luxury-editorial',
  },

  // ===== B2B 6 =====
  'saas-software': {
    key: 'saas-software',
    displayName: 'SaaS 軟體',
    category: 'b2b',
    recommendedSiteTypes: ['lp', 'cms', 'blog'],
    recommendedModules: ['lp.ab-test', 'marketing.email-campaigns', 'marketing.segments'],
    recommendedPresetId: 'modern-minimal',
  },
  consulting: {
    key: 'consulting',
    displayName: '管理顧問',
    category: 'b2b',
    recommendedSiteTypes: ['lp', 'cms', 'blog'],
    recommendedModules: ['marketing.email-campaigns'],
    recommendedPresetId: 'corporate-trust',
  },
  manufacturing: {
    key: 'manufacturing',
    displayName: '製造業',
    category: 'b2b',
    recommendedSiteTypes: ['cms', 'lp'],
    recommendedModules: ['marketing.email-campaigns'],
    recommendedPresetId: 'corporate-trust',
  },
  'print-design': {
    key: 'print-design',
    displayName: '印刷設計',
    category: 'b2b',
    recommendedSiteTypes: ['shop', 'cms'],
    recommendedModules: ['shop.product-variants'],
    recommendedPresetId: 'magazine-editorial',
  },
  'logistics-trade': {
    key: 'logistics-trade',
    displayName: '物流貿易',
    category: 'b2b',
    recommendedSiteTypes: ['lp', 'cms'],
    recommendedModules: ['marketing.email-campaigns'],
    recommendedPresetId: 'corporate-trust',
  },
  'legal-accounting': {
    key: 'legal-accounting',
    displayName: '法律會計',
    category: 'b2b',
    recommendedSiteTypes: ['lp', 'cms', 'blog'],
    recommendedModules: ['lp.sticky-cta', 'marketing.email-campaigns'],
    recommendedPresetId: 'corporate-trust',
  },

  // ===== 特殊 9 =====
  'ai-web3': {
    key: 'ai-web3',
    displayName: 'AI / Web3',
    category: 'special',
    recommendedSiteTypes: ['lp', 'cms'],
    recommendedModules: ['lp.ab-test', 'marketing.retargeting'],
    recommendedPresetId: 'cyber-tech',
  },
  realestate: {
    key: 'realestate',
    displayName: '不動產',
    category: 'special',
    recommendedSiteTypes: ['cms', 'lp'],
    recommendedModules: ['lp.sticky-cta', 'marketing.email-campaigns'],
    recommendedPresetId: 'realestate-prestige',
  },
  crowdfunding: {
    key: 'crowdfunding',
    displayName: '群眾募資',
    category: 'special',
    recommendedSiteTypes: ['lp', 'course'],
    recommendedModules: [
      'course.crowdfunding',
      'lp.countdown',
      'lp.ab-test',
      'marketing.referral',
    ],
    recommendedPresetId: 'crowdfund-energy',
  },
  nonprofit: {
    key: 'nonprofit',
    displayName: '非營利組織',
    category: 'special',
    recommendedSiteTypes: ['lp', 'cms', 'blog'],
    recommendedModules: ['marketing.email-campaigns', 'marketing.referral'],
    recommendedPresetId: 'civic-bold',
  },
  'personal-brand': {
    key: 'personal-brand',
    displayName: '個人品牌',
    category: 'special',
    recommendedSiteTypes: ['blog', 'cms', 'lp'],
    recommendedModules: ['marketing.email-campaigns'],
    recommendedPresetId: 'modern-minimal',
  },
  'event-conference': {
    key: 'event-conference',
    displayName: '活動會議',
    category: 'special',
    recommendedSiteTypes: ['lp', 'cms'],
    recommendedModules: ['lp.countdown', 'lp.sticky-cta', 'marketing.email-campaigns'],
    recommendedPresetId: 'playful-bold',
  },
  'nightclub-bar': {
    key: 'nightclub-bar',
    displayName: '夜店酒吧',
    category: 'special',
    recommendedSiteTypes: ['lp', 'cms'],
    recommendedModules: ['marketing.line-marketing'],
    recommendedPresetId: 'nightclub-neon',
  },
  'church-religion': {
    key: 'church-religion',
    displayName: '宗教信仰',
    category: 'special',
    recommendedSiteTypes: ['cms', 'lp', 'blog'],
    recommendedModules: ['marketing.email-campaigns'],
    recommendedPresetId: 'sacred-serenity',
  },
  'political-campaign': {
    key: 'political-campaign',
    displayName: '選舉造勢',
    category: 'special',
    recommendedSiteTypes: ['lp', 'cms', 'blog'],
    recommendedModules: ['lp.countdown', 'marketing.email-campaigns', 'marketing.referral'],
    recommendedPresetId: 'civic-bold',
  },
};
